spring.application.name=api

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://darsiuz.ddns.net:2012/grupo7_db1
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=querecot2396
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Ver el SQL en consola
spring.jpa.show-sql=true

# JWT
jwt.secret=cine-api-secret-key-super-segura-2024-no-compartir
jwt.expiration=86400000